import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, Activity, Users, AlertTriangle, ArrowRight } from 'lucide-react';

const Landing = () => {
    return (
        <div className="space-y-20">
            {/* Hero Section */}
            <section className="text-center space-y-8 py-10 md:py-20">
                <div className="inline-flex items-center bg-blue-50 text-primary px-4 py-2 rounded-full font-medium text-sm">
                    <Activity size={16} className="mr-2" />
                    AI-Powered Medication Safety Assistant
                </div>
                <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-gray-900 leading-tight">
                    Your Personal Shield Against <br />
                    <span className="text-primary bg-gradient-to-r from-blue-600 to-teal-400 bg-clip-text text-transparent">Medication Errors</span>
                </h1>
                <p className="text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
                    Instantly analyze your prescriptions for dangerous interactions, dosage conflicts, and timing risks using our advanced AI-based awareness system.
                </p>
                <div className="flex flex-col sm:flex-row justify-center gap-4 mt-8">
                    <Link to="/register" className="bg-primary hover:bg-blue-700 text-white text-lg px-8 py-4 rounded-full font-bold shadow-lg shadow-blue-500/30 transition-all flex items-center justify-center">
                        Check My Meds Now <ArrowRight className="ml-2" />
                    </Link>
                    <Link to="/login" className="bg-white hover:bg-gray-50 text-gray-700 text-lg px-8 py-4 rounded-full font-bold border border-gray-200 shadow-sm transition-all">
                        Login to Dashboard
                    </Link>
                </div>
            </section>

            {/* Features Grid */}
            <section className="grid md:grid-cols-3 gap-8">
                <FeatureCard
                    icon={<ShieldCheck className="text-teal-500" size={40} />}
                    title="Interaction Checker"
                    description="Identify potential conflicts between multiple medications instantly."
                />
                <FeatureCard
                    icon={<Users className="text-blue-500" size={40} />}
                    title="Family Profiles"
                    description="Manage medication safety for your parents, children, or dependents in one place."
                />
                <FeatureCard
                    icon={<Activity className="text-purple-500" size={40} />}
                    title="Risk Analysis"
                    description="Get simple, easy-to-understand risk scores and awareness summaries."
                />
            </section>

            {/* Disclaimer Banner (Sticky or Prominent) */}
            <section className="bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg shadow-sm">
                <div className="flex items-start">
                    <AlertTriangle className="text-amber-600 min-w-[24px] mr-4 mt-1" />
                    <div>
                        <h3 className="text-amber-800 font-bold text-lg mb-1">Medical Disclaimer</h3>
                        <p className="text-amber-700 text-sm leading-relaxed">
                            This platform is an <strong>assistive tool only</strong> and does not provide medical advice, diagnosis, or treatment.
                            The risk analysis is generated by AI and may not be 100% accurate. Always consult your doctor or pharmacist
                            before making any changes to your medication regimen.
                        </p>
                    </div>
                </div>
            </section>
        </div>
    );
};

const FeatureCard = ({ icon, title, description }) => (
    <div className="bg-white p-8 rounded-2xl shadow-soft card-hover border border-gray-100">
        <div className="mb-4 bg-gray-50 w-16 h-16 rounded-2xl flex items-center justify-center">
            {icon}
        </div>
        <h3 className="text-xl font-bold mb-3 text-gray-800">{title}</h3>
        <p className="text-gray-600 leading-relaxed">
            {description}
        </p>
    </div>
);

export default Landing;
